accounts/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, url


urlpatterns = patterns("reviewboard.accounts.views",
    url(r'^register/$', 'account_register',
        { 'next_url': 'dashboard' }, name="register"),
    url(r'^preferences/$', 'user_preferences', name="user-preferences"),
)

urlpatterns += patterns("djblets.auth.views",
    url(r'^login/$',
        'login',
        {'next_page': settings.SITE_ROOT + 'dashboard/'},
        name="login"),
)

urlpatterns += patterns("django.contrib.auth.views",
    url(r'^recover/$',
        'password_reset',
        {'template_name': 'accounts/password_reset.html',
         'email_template_name': 'accounts/password_reset_email.txt'},
        name='recover'),
    url(r'^recover/done/$',
        'password_reset_done',
        {'template_name': 'accounts/password_reset_done.html'}),
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'password_reset_confirm',
        {'template_name': 'accounts/password_reset_confirm.html'},
        name='password-reset-confirm'),
    url(r'^reset/done/$',
        'password_reset_complete',
        {'template_name': 'accounts/password_reset_complete.html'}),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from reviewboard.webapi.resources import root_resource
from reviewboard import initialize


initialize()


handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'


# Load in all the models for the admin UI.
if not admin.site._registry:
    admin.autodiscover()


# URLs global to all modes
urlpatterns = patterns('',
    (r'^admin/', include('reviewboard.admin.urls')),
)

# Add static media if running in DEBUG mode
if settings.DEBUG or getattr(settings, 'RUNNING_TEST', False):
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve', {
            'show_indexes': True,
            'document_root': settings.MEDIA_ROOT,
        })
    )

localsite_urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.redirect_to',
        {'url': 'dashboard/'},
        name="root"),

    (r'^api/', include(root_resource.get_url_patterns())),
    (r'^r/', include('reviewboard.reviews.urls')),

    # Dashboard
    url(r'^dashboard/$',
        'reviewboard.reviews.views.dashboard', name="dashboard"),

    # Users
    url(r'^users/$',
        'reviewboard.reviews.views.submitter_list', name="all-users"),
    url(r'^users/(?P<username>[A-Za-z0-9@_\-\.]+)/$',
        'reviewboard.reviews.views.submitter', name="user"),
    url(r'^users/(?P<username>[A-Za-z0-9@_\-\.]+)/infobox/$',
        'reviewboard.reviews.views.user_infobox', name="user-infobox"),

    # Groups
    url(r'^groups/$',
        'reviewboard.reviews.views.group_list', name="all-groups"),
    url(r'^groups/(?P<name>[A-Za-z0-9_-]+)/$',
        'reviewboard.reviews.views.group', name="group"),
    url(r'^groups/(?P<name>[A-Za-z0-9_-]+)/members/$',
        'reviewboard.reviews.views.group_members', name="group_members"),
)


# Main includes
urlpatterns += patterns('',
    (r'^account/', include('reviewboard.accounts.urls')),
    (r'^reports/', include('reviewboard.reports.urls')),

    (r'^s/(?P<local_site_name>[A-Za-z0-9\-_.]+)/',
     include(localsite_urlpatterns)),
)

urlpatterns += localsite_urlpatterns


# django.contrib
urlpatterns += patterns('django.contrib',
    url(r'^account/logout/$', 'auth.views.logout',
        {'next_page': settings.LOGIN_URL}, name="logout")
)

accounts/forms.py
import re
import sre_constants

from django import forms
from django.forms import widgets
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from djblets.auth.forms import RegistrationForm as DjbletsRegistrationForm
from djblets.siteconfig.forms import SiteSettingsForm
from djblets.siteconfig.models import SiteConfiguration
from recaptcha.client import captcha

from reviewboard.admin.checks import get_can_enable_dns, \
                                     get_can_enable_ldap
from reviewboard.reviews.models import Group


class PreferencesForm(forms.Form):
    redirect_to = forms.CharField(required=False, widget=forms.HiddenInput)
    groups = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                       required=False)
    syntax_highlighting = forms.BooleanField(required=False,
        label=_("Enable syntax highlighting in the diff viewer"))
    profile_private = forms.BooleanField(required=False,
        label=_("Keep your user profile private"))
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField()
    password1 = forms.CharField(required=False, widget=widgets.PasswordInput())
    password2 = forms.CharField(required=False, widget=widgets.PasswordInput())

    def __init__(self, user, *args, **kwargs):
        from reviewboard.accounts.backends import get_auth_backends

        super(forms.Form, self).__init__(*args, **kwargs)

        auth_backends = get_auth_backends()
        choices = []

        for g in Group.objects.accessible(user=user).order_by('display_name'):
            choices.append((g.id, g.display_name))

        for site in user.local_site.all().order_by('name'):
            for g in Group.objects.accessible(
                user=user, local_site=site).order_by('display_name'):
                display_name = '%s / %s' % (g.local_site.name, g.display_name)
                choices.append((g.id, display_name))

        self.fields['groups'].choices = choices
        self.fields['email'].required = auth_backends[0].supports_change_email

    def save(self, user):
        from reviewboard.accounts.backends import get_auth_backends

        auth_backends = get_auth_backends()
        primary_backend = auth_backends[0]

        password = self.cleaned_data['password1']

        if primary_backend.supports_change_password and password:
            primary_backend.update_password(user, password)

        if primary_backend.supports_change_name:
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            primary_backend.update_name(user)

        if primary_backend.supports_change_email:
            user.email = self.cleaned_data['email']
            primary_backend.update_email(user)

        user.review_groups = self.cleaned_data['groups']
        user.save()

        profile = user.get_profile()
        profile.first_time_setup_done = True
        profile.syntax_highlighting = self.cleaned_data['syntax_highlighting']
        profile.is_private = self.cleaned_data['profile_private']
        profile.save()

    def clean_password2(self):
        p1 = self.cleaned_data['password1']
        p2 = self.cleaned_data['password2']
        if p1 != p2:
            raise forms.ValidationError('passwords do not match')
        return p2


class RegistrationForm(DjbletsRegistrationForm):
    """A registration form with reCAPTCHA support.

    This is a version of the Djblets RegistrationForm which knows how to
    validate a reCAPTCHA widget. Any error received is stored in the form
    for use when generating the widget so that the widget can properly display
    the error.
    """
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    recaptcha_challenge_field = forms.CharField(required=False)
    recaptcha_response_field = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.captcha_error_query_str = ""

        siteconfig = SiteConfiguration.objects.get_current()

        if siteconfig.get('site_domain_method') == 'https':
            self.recaptcha_url = 'https://api-secure.recaptcha.net'
        else:
            self.recaptcha_url = 'http://api.recaptcha.net'

    def clean(self):
        siteconfig = SiteConfiguration.objects.get_current()

        if siteconfig.get('auth_registration_show_captcha'):
            challenge = self.cleaned_data.get('recaptcha_challenge_field', None)
            response = self.cleaned_data.get('recaptcha_response_field', None)

            if challenge and response:
                captcha_response = \
                    captcha.submit(
                        challenge,
                        response,
                        siteconfig.get('recaptcha_private_key'),
                        self.request.META.get('REMOTE_ADDR', None))

                if not captcha_response.is_valid:
                    self.captcha_error_query_str = '&error=%s' % \
                        captcha_response.error_code

                    # This isn't actually seen in the Review Board UI,
                    # as the reCAPTCHA widget itself displays the error
                    # message. However, this may be useful for testing or
                    # debugging.
                    raise forms.ValidationError(
                        _("The text you entered didn't match what was "
                          "displayed"))
            else:
                self.captcha_error_query_str = '&error=incorrect-captcha-sol'

                raise forms.ValidationError(
                    _('You need to respond to the captcha'))

        return super(RegistrationForm, self).clean()

    def save(self):
        user = DjbletsRegistrationForm.save(self)

        if user:
            user.first_name = self.cleaned_data['first_name']
            user.last_name = self.cleaned_data['last_name']
            user.save()

        return user


class ActiveDirectorySettingsForm(SiteSettingsForm):
    auth_ad_domain_name = forms.CharField(
        label=_("Domain name"),
        help_text=_("Enter the domain name to use, (ie. example.com). This will be "
                    "used to query for LDAP servers and to bind to the domain."),
        required=True)

    auth_ad_use_tls = forms.BooleanField(
        label=_("Use TLS for authentication"),
        required=False)

    auth_ad_find_dc_from_dns = forms.BooleanField(
        label=_("Find DC from DNS"),
        help_text=_("Query DNS to find which domain controller to use"),
        required=False)

    auth_ad_domain_controller = forms.CharField(
        label=_("Domain controller"),
        help_text=_("If not using DNS to find the DC specify the domain "
                    "controller here"),
        required=False)

    auth_ad_ou_name = forms.CharField(
        label=_("OU name"),
        help_text=_("Optionally restrict users to specified OU."),
        required=False)

    auth_ad_group_name = forms.CharField(
        label=_("Group name"),
        help_text=_("Optionally restrict users to specified group."),
        required=False)

    auth_ad_search_root = forms.CharField(
        label=_("Custom search root"),
        help_text=_("Optionally specify a custom search root, overriding "
                    "the built-in computed search root. If set, \"OU name\" "
                    "is ignored."),
        required=False)

    auth_ad_recursion_depth = forms.IntegerField(
        label=_("Recursion Depth"),
        help_text=_('Depth to recurse when checking group membership. '
                    '0 to turn off, -1 for unlimited.'),
        required=False)

    def load(self):
        can_enable_dns, reason = get_can_enable_dns()

        if not can_enable_dns:
            self.disabled_fields['auth_ad_find_dc_from_dns'] = reason

        can_enable_ldap, reason = get_can_enable_ldap()

        if not can_enable_ldap:
            self.disabled_fields['auth_ad_use_tls'] = True
            self.disabled_fields['auth_ad_group_name'] = True
            self.disabled_fields['auth_ad_recursion_depth'] = True
            self.disabled_fields['auth_ad_ou_name'] = True
            self.disabled_fields['auth_ad_search_root'] = True
            self.disabled_fields['auth_ad_find_dc_from_dns'] = True
            self.disabled_fields['auth_ad_domain_controller'] = True

            self.disabled_reasons['auth_ad_domain_name'] = reason

        super(ActiveDirectorySettingsForm, self).load()

    class Meta:
        title = _('Active Directory Authentication Settings')


class StandardAuthSettingsForm(SiteSettingsForm):
    auth_enable_registration = forms.BooleanField(
        label=_("Enable registration"),
        help_text=_("Allow users to register new accounts."),
        required=False)

    auth_registration_show_captcha = forms.BooleanField(
        label=_('Show a captcha for registration'),
        help_text=mark_safe(
            _('Displays a captcha using <a href="%(recaptcha_url)s">'
              'reCAPTCHA</a> on the registration page. To enable this, you '
              'will need to go <a href="%(register_url)s">here</A> to register '
              'an account and type in your new keys below.') % {
                  'recaptcha_url': 'http://www.recaptcha.net/',
                  'register_url': 'https://admin.recaptcha.net/recaptcha'
                                  '/createsite/',
            }),
        required=False)

    recaptcha_public_key = forms.CharField(
        label=_('reCAPTCHA Public Key'),
        required=False,
        widget=forms.TextInput(attrs={'size': '40'}))

    recaptcha_private_key = forms.CharField(
        label=_('reCAPTCHA Private Key'),
        required=False,
        widget=forms.TextInput(attrs={'size': '40'}))

accounts/views.py
from django.conf import settings
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from djblets.auth.util import login_required
from djblets.auth.views import register
from djblets.siteconfig.models import SiteConfiguration

from reviewboard.accounts.backends import get_auth_backends
from reviewboard.accounts.forms import PreferencesForm, RegistrationForm
from reviewboard.accounts.models import Profile
from reviewboard.accounts.signals import user_registered


def account_register(request, next_url='dashboard'):
    """
    Handles redirection to the appropriate registration page, depending
    on the authentication type the user has configured.
    """
    siteconfig = SiteConfiguration.objects.get_current()
    auth_backends = get_auth_backends()

    if (auth_backends[0].supports_registration and
        siteconfig.get("auth_enable_registration")):
        response = register(request, next_page=reverse(next_url),
                            form_class=RegistrationForm)

        if request.user.is_authenticated():
            # This will trigger sending an e-mail notification for
            # user registration, if enabled.
            user_registered.send(sender=None, user=request.user)

        return response

    return HttpResponseRedirect(reverse("login"))


@login_required
def user_preferences(request, template_name='accounts/prefs.html'):
    # TODO: Figure out the right place to redirect when using a LocalSite.
    redirect_to = \
        request.REQUEST.get(REDIRECT_FIELD_NAME,
            request.REQUEST.get('redirect_to', None))

    if not redirect_to:
        redirect_to = reverse("dashboard")

    profile, profile_is_new = \
        Profile.objects.get_or_create(user=request.user)
    profile.save()

    auth_backends = get_auth_backends()

    if request.POST:
        form = PreferencesForm(request.user, request.POST)

        if form.is_valid():
            form.save(request.user)

            return HttpResponseRedirect(redirect_to)
    else:
        form = PreferencesForm(request.user, {
            'settings': settings,
            'redirect_to': redirect_to,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'syntax_highlighting': profile.syntax_highlighting,
            'profile_private': profile.is_private,
            'groups': [g.id for g in request.user.review_groups.all()],
        })

    return render_to_response(template_name, RequestContext(request, {
        'form': form,
        'settings': settings,
        'can_change_password': auth_backends[0].supports_change_password,
    }))

templates/accounts/login.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load djblets_utils %}
{% load i18n %}

{% block title %}{% trans "Log In" %}{% endblock %}

{% block content %}
{%  if not auth_backends.0.supports_registration %}
{%  box "important" %}
<h1>{% trans "Log in with your standard username and password" %}</h1>
 <p>
 {% blocktrans %}There's no need to register a new account. Your standard username and password should work fine.{% endblocktrans %}
 </p>
{%  endbox %}
{% endif%}

{% box "loginform" %}
<form method="post" action=".">
 <h1 class="title">{% trans "Log In" %}</h1>
 <div class="main">
 {% if error %}
 {%  errorbox %}
 {{ error }}
 {%  enderrorbox %}
 {% endif %}
 <input type="hidden" name="next_page" value="{{next_page}}"></input>
 <table>
  <tr>
   <td class="label"><label for="id_username">{% trans "Username" %}</label></td>
   <td class="field"><input type="text" name="username" id="id_username" tabindex="1" /></td>
{% if auth_backends.0.supports_registration and siteconfig.settings.auth_enable_registration|default_if_none:1 %}
   <td class="hint">
    {% trans "Don't have an account?" %}
    <a href="{% url register %}">{% trans "Create one now" %}</a>
   </td>
{% endif %}
  </tr>
  <tr>
   <td class="label"><label for="id_password">{% trans "Password" %}</label></td>
   <td class="field"><input type="password" name="password" id="id_password" tabindex="2" /></td>
{% if auth_backends.0.supports_registration %}
   <td class="hint">
    {% trans "Forgot your password?" %}
    <a href="{% url recover %}">{% trans "Recover it" %}</a>
   </td>
{% endif %}
  </tr>
  <tr>
   <td>&nbsp;</td>
   <td class="field"><input type="submit" value="{% trans "Log in" %}" tabindex="3" /></td>
  </tr>
 </table>
 </div>
</form>
{% endbox %}

{% endblock %}

templates/accounts/password_reset.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}

{% block title %}{% trans "Recover Password" %}{% endblock %}

{% block content %}
{% box "passwordreset" %}
 <form method="post" action=".">

  {# This should really use {% csrf_token %}, but we can't until we #}
  {# move to Django 1.2 in a future release.                        #}
  {% if csrf_token %}
  {%  ifnotequal csrf_token "NOTPROVIDED" %}
  <div style="display: none;"><input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" /></div>
  {%  endifnotequal %}

  {% endif %}
  <h1 class="title">{% trans "Recover Password" %}</h1>
  <div class="main">
   <p>{% blocktrans %}Forgotten your password? Enter your e-mail address, and
   we'll send you instructions for creating a new one.{% endblocktrans %}</p>
   <table>
    <tr>
     <td class="label"><label for="id_email">{% trans "E-mail address" %}</label></td>
     <td class="field"><input type="text" name="email" id="id_email" /></td>
     <td class="field"><input type="submit" value="{% trans "Recover" %}" /></td>
    </tr>
   </table>
  </div>
 </form>
{% endbox %}
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}

{% block title %}{% trans "Password reset complete" %}{% endblock %}

{% block content %}
{% box "passwordreset" %}
<h1 class="title">{% trans "Password reset complete" %}</h1>
<div class="main">
 <p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>
 <p><a href="{% url login %}">{% trans "Log in." %}</a></p>
</div>
{% endbox %}
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}

{% block title %}{% trans "Recover Password" %}{% endblock %}

{% block content %}
{%  box "passwordreset" %}
{%   if validlink %}
      <form method="post" action=".">
       <h1 class="title">{% trans "Enter new password" %}</h1>
       <div class="main">
	<p>{% blocktrans %}Please enter your new password twice so we can
	verify you typed it in correctly.{% endblocktrans %}</p>
        <table>
         <tr>
          <td class="label"><label for="id_new_password1">{% trans "New password" %}</label></td>
          <td class="field">{{form.new_password1}}</td>
          <td class="hint">{{form.new_password1.errors}}</td>
         </tr>
         <tr>
          <td class="label"><label for="id_new_password2">{% trans "Confirm password" %}</label></td>
          <td class="field">{{form.new_password2}}</td>
          <td class="hint">{{form.new_password2.errors}}</td>
         </tr>
         <tr>
          <td class="label">&nbsp;</td>
          <td class="field"><input type="submit" value="{% trans "Change my password" %}" /></td>
          <td class="hint">&nbsp;</td>
	 </tr>
        </table>
       </div>
      </form>
{%   else %}
      <h1 class="title">{% trans "Password reset unsuccessful" %}</h1>
      <div class="main">
       {% url recover as recover_url %}
       <p>{% blocktrans %}The password reset link was invalid, either because
       it expired or has already been used. Please request a new one
       <a href="{{recover_url}}">here</a>.{% endblocktrans %}</p>
      </div>
{%   endif %}
{%  endbox %}
{% endblock %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}

{% block title %}{% trans "Password Reset Successful" %}{% endblock %}

{% block content %}
{% box "passwordreset" %}
 <h1 class="title">{% trans "Password reset successful" %}</h1>
 <div class="main">
  <p>{% blocktrans %}We've e-mailed you instructions for setting your password
  to the e-mail address you submitted. You should be receiving it shortly.
  {% endblocktrans %}</p>
 </div>
{% endbox %}
{% endblock %}

templates/accounts/prefs.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}
{% block title %}{% trans "My Account" %}{% endblock %}

{% block content %}
<form method="post" action=".">
 {{form.redirect_to}}
{% box "prefsuser" %}
 <h1 class="title">{% trans "User Preferences" %}</h1>
 <div class="main">
  <table>
{% if auth_backends.0.supports_change_name %}
   <tr>
    <td><label for="id_first_name">{% trans "First Name:" %}</label></td>
    <td>{{form.first_name}}</td>
   </tr>
   <tr>
    <td><label for="id_last_name">{% trans "Last Name:" %}</label></td>
    <td>{{form.last_name}}</td>
   </tr>
{% endif %}
{% if auth_backends.0.supports_change_email %}
   <tr>
    <td><label for="id_email">{% trans "Email:" %}</label></td>
    <td>{{form.email}} {{form.errors.email}}</td>
   </tr>
{% endif %}
{% if auth_backends.0.supports_change_password %}
   <tr>
    <td><label for="id_password">{% trans "Change Password:" %}</label></td>
    <td>{{form.password1}}</td>
   </tr>
   <tr>
    <td><label for="id_password2">{% trans "Verify New Password:" %}</label></td>
    <td>{{form.password2}} {{form.errors.password2}}</td>
   </tr>
{% endif %}
{% if siteconfig.settings.diffviewer_syntax_highlighting %}
   <tr>
    <td></td>
    <td>{{form.syntax_highlighting}} {{form.syntax_highlighting.label}}</td>
   </tr>
{% endif %}
   <tr>
    <td></td>
    <td>{{form.profile_private}} {{form.profile_private.label}}</td>
   </tr>
  </table>
 </div>
{% endbox %}
{% if form.fields.groups.choices %}
{% box "prefsgroup" %}
 <h1 class="title">{% trans "Groups" %}</h1>
 <div class="main">
  <p>{% trans "Which groups do you belong to or wish to watch?" %}</p>
  {{form.groups}}
 </div>
{% endbox %}
{% endif %}
 <div class="prefsbuttons">
  <input type="submit" value="{% trans "Save Preferences" %}" />
 </div>
</form>

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}
{% block title %}{% trans "Register account" %}{% endblock %}

{% block content %}
{% box "registerform" %}
<form method="post" action=".">
 <h1 class="title">{% trans "Register" %}</h1>
 <div class="main">
  <table id="login_form">
   <tr>
    <td class="label"><label for="id_username">{% trans "Username:" %}</label></td>
    <td class="field">{{form.username}}</td>
    <td class="errorbox">{{form.errors.username}}</td>
   </tr>
   <tr>
    <td class="label"><label for="id_password1">{% trans "Password:" %}</label></td>
    <td class="field">{{form.password1}}</td>
    <td class="errorbox">{{form.errors.password1}}</td>
   </tr>
   <tr>
    <td class="label"><label for="id_password2">{% trans "Password (repeat):" %}</label></td>
    <td class="field">{{form.password2}}</td>
    <td class="errorbox">{{form.errors.password2}}</td>
   </tr>
   <tr>
    <td class="label"><label for="id_email">{% trans "E-mail address:" %}</label></td>
    <td class="field">{{form.email}}</td>
    <td class="errorbox">{{form.errors.email}}</td>
   </tr>
   <tr>
    <td class="label"><label for="id_first_name">{% trans "First name:" %}</label></td>
    <td class="field">{{form.first_name}}</td>
    <td class="errorbox">{{form.errors.first_name}}</td>
   </tr>
   <tr>
    <td class="label"><label for="id_last_name">{% trans "Last name:" %}</label></td>
    <td class="field">{{form.last_name}}</td>
    <td class="errorbox">{{form.errors.last_name}}</td>
   </tr>
{% if siteconfig.settings.auth_registration_show_captcha %}
   <tr>
    <td></td>
	<td colspan="2">
	 <script type="text/javascript" src="{{form.recaptcha_url}}/challenge?k={{siteconfig.settings.recaptcha_public_key}}{{form.captcha_error_query_str}}">
	 </script>

	 <noscript>
	  <iframe src="{{form.recaptcha_url}}/noscript?k={{siteconfig.settings.recaptcha_public_key}}{{form.captcha_error_query_str}}"
	          height="300" width="500" frameborder="0"></iframe>
      <br />
	  <textarea name="recaptcha_challenge_field" rows="3" cols="40">
	  </textarea>
	  <input type="hidden" name="recaptcha_response_field" value="manual_challenge" />
	 </noscript>
	</td>
   </tr>
{% endif %}
   <tr>
    <td><input type="submit" value="{% trans "Register" %}" /></td>
    <td>&nbsp;</td>
   </tr>
  </table>
 </div>
</form>
{% endbox %}
{% endblock %}

templates/accounts/user_infobox.html
{% load i18n %}
{% load djblets_deco %}
{% load djblets_utils %}
{% load gravatars %}
{% load reviewtags %}

<div class="infobox-content" class="vcard">
 <div class="infobox-pic" class="logo">
  {% gravatar requested_user 85 %}
 </div>
 <div class="infobox-text">
  <h2 class="nickname">{{requested_user}}</h2>
{% if show_profile %}
  <p class="fn">{{requested_user.first_name}} {{requested_user.last_name}}</p>
{% if request.user.is_authenticated %}
  <p class="email">{{requested_user.email}}</p>
{% endif %}
  <p class="logged-in">Last logged in {{requested_user.last_login|date:"F jS, Y"}}</p>
  <p class="joined">Joined {{requested_user.date_joined|date:"F jS, Y"}}</p>
{% endif %}
 </div>
</div>