reviews/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('reviewboard.reviews.views',
    url(r'^$', 'all_review_requests', name="all-review-requests"),

    # Review request creation
    url(r'^new/$', 'new_review_request', name="new-review-request"),
    url(r'^newpost/$', 'new_post_review_request', name="new-post-review-request"),

    # Review request detail
    url(r'^(?P<review_request_id>[0-9]+)/$', 'review_detail',
        name="review-request-detail"),

    # Reviews
    (r'^(?P<review_request_id>[0-9]+)/reviews/draft/inline-form/$',
     'review_draft_inline_form',
     {'template_name': 'reviews/review_draft_inline_form.html'}),

    # Review request diffs
    url(r'^(?P<review_request_id>[0-9]+)/diff/$', 'diff', name="view_diff"),
    url(r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)/$', 'diff',
        name="view_diff_revision"),

    url(r'^(?P<review_request_id>[0-9]+)/diff/raw/$', 'raw_diff',
        name='raw_diff'),
    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)/raw/$',
     'raw_diff'),

    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)/fragment/(?P<filediff_id>[0-9]+)/$',
     'diff_fragment'),
    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)/fragment/(?P<filediff_id>[0-9]+)/chunk/(?P<chunkindex>[0-9]+)/$',
     'diff_fragment'),

    # Fragments
    (r'^(?P<review_request_id>[0-9]+)/fragments/diff-comments/(?P<comment_ids>[0-9,]+)/$',
     'comment_diff_fragments'),

    # Review request interdiffs
    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)-(?P<interdiff_revision>[0-9]+)/$',
     'diff'),
    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)-(?P<interdiff_revision>[0-9]+)/fragment/(?P<filediff_id>[0-9]+)/$',
     'diff_fragment'),
    (r'^(?P<review_request_id>[0-9]+)/diff/(?P<revision>[0-9]+)-(?P<interdiff_revision>[0-9]+)/fragment/(?P<filediff_id>[0-9]+)/chunk/(?P<chunkindex>[0-9]+)/$',
     'diff_fragment'),

    # Screenshots
    url(r'^(?P<review_request_id>[0-9]+)/s/(?P<screenshot_id>[0-9]+)/$',
        'view_screenshot',
        name='screenshot'),

    # E-mail previews
    (r'^(?P<review_request_id>[0-9]+)/preview-email/(?P<format>(text|html))/$',
     'preview_review_request_email'),
    (r'^(?P<review_request_id>[0-9]+)/reviews/(?P<review_id>[0-9]+)/preview-email/(?P<format>(text|html))/$',
     'preview_review_email'),
    (r'^(?P<review_request_id>[0-9]+)/reviews/(?P<review_id>[0-9]+)/replies/(?P<reply_id>[0-9]+)/preview-email/(?P<format>(text|html))/$',
     'preview_reply_email'),

    # Search
    url(r'^search/$', 'search', name="search"),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from reviewboard.webapi.resources import root_resource
from reviewboard import initialize


initialize()


handler404 = 'django.views.defaults.page_not_found'
handler500 = 'django.views.defaults.server_error'


# Load in all the models for the admin UI.
if not admin.site._registry:
    admin.autodiscover()


# URLs global to all modes
urlpatterns = patterns('',
    (r'^admin/', include('reviewboard.admin.urls')),
)

# Add static media if running in DEBUG mode
if settings.DEBUG or getattr(settings, 'RUNNING_TEST', False):
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve', {
            'show_indexes': True,
            'document_root': settings.MEDIA_ROOT,
        })
    )

localsite_urlpatterns = patterns('',
    url(r'^$', 'django.views.generic.simple.redirect_to',
        {'url': 'dashboard/'},
        name="root"),

    (r'^api/', include(root_resource.get_url_patterns())),
    (r'^r/', include('reviewboard.reviews.urls')),

    # Dashboard
    url(r'^dashboard/$',
        'reviewboard.reviews.views.dashboard', name="dashboard"),

    # Users
    url(r'^users/$',
        'reviewboard.reviews.views.submitter_list', name="all-users"),
    url(r'^users/(?P<username>[A-Za-z0-9@_\-\.]+)/$',
        'reviewboard.reviews.views.submitter', name="user"),
    url(r'^users/(?P<username>[A-Za-z0-9@_\-\.]+)/infobox/$',
        'reviewboard.reviews.views.user_infobox', name="user-infobox"),

    # Groups
    url(r'^groups/$',
        'reviewboard.reviews.views.group_list', name="all-groups"),
    url(r'^groups/(?P<name>[A-Za-z0-9_-]+)/$',
        'reviewboard.reviews.views.group', name="group"),
    url(r'^groups/(?P<name>[A-Za-z0-9_-]+)/members/$',
        'reviewboard.reviews.views.group_members', name="group_members"),
)


# Main includes
urlpatterns += patterns('',
    (r'^account/', include('reviewboard.accounts.urls')),
    (r'^reports/', include('reviewboard.reports.urls')),

    (r'^s/(?P<local_site_name>[A-Za-z0-9\-_.]+)/',
     include(localsite_urlpatterns)),
)

urlpatterns += localsite_urlpatterns


# django.contrib
urlpatterns += patterns('django.contrib',
    url(r'^account/logout/$', 'auth.views.logout',
        {'next_page': settings.LOGIN_URL}, name="logout")
)

reviews/models.py
import os
import re
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from djblets.util.db import ConcurrencyManager
from djblets.util.fields import CounterField, ModificationTimestampField
from djblets.util.misc import get_object_or_none
from djblets.util.templatetags.djblets_images import crop_image, thumbnail

from reviewboard.changedescs.models import ChangeDescription
from reviewboard.diffviewer.models import DiffSet, DiffSetHistory, FileDiff
from reviewboard.attachments.models import FileAttachment
from reviewboard.reviews.signals import review_request_published, \
                                        review_request_reopened, \
                                        review_request_closed, \
                                        reply_published, review_published
from reviewboard.reviews.errors import PermissionError
from reviewboard.reviews.managers import DefaultReviewerManager, \
                                         ReviewGroupManager, \
                                         ReviewRequestManager, \
                                         ReviewManager
from reviewboard.scmtools.errors import EmptyChangeSetError, \
                                        InvalidChangeNumberError
from reviewboard.scmtools.models import Repository
from reviewboard.site.models import LocalSite
from reviewboard.site.urlresolvers import local_site_reverse


# The model for the review request summary only allows it to be 300 chars long
MAX_SUMMARY_LENGTH = 300


def update_obj_with_changenum(obj, repository, changenum):
    """
    Utility helper to update a review request or draft from the
    specified changeset's contents on the server.
    """
    changeset = repository.get_scmtool().get_changeset(changenum)

    if not changeset:
        raise InvalidChangeNumberError()

    # If the SCM supports changesets, they should always include a number,
    # summary and description, parsed from the changeset description. Some
    # specialized systems may support the other fields, but we don't want to
    # clobber the user-entered values if they don't.
    obj.changenum = changenum
    obj.summary = changeset.summary
    obj.description = changeset.description
    if changeset.testing_done:
        obj.testing_done = changeset.testing_done
    if changeset.branch:
        obj.branch = changeset.branch
    if changeset.bugs_closed:
        obj.bugs_closed = ','.join(changeset.bugs_closed)


def truncate(string, num):
   if len(string) > num:
      string = string[0:num]
      i = string.rfind('.')

      if i != -1:
         string = string[0:i + 1]

   return string


class Group(models.Model):
    """
    A group of reviewers identified by a name. This is usually used to
    separate teams at a company or components of a project.

    Each group can have an e-mail address associated with it, sending
    all review requests and replies to that address. If that e-mail address is
    blank, e-mails are sent individually to each member of that group.
    """
    name = models.SlugField(_("name"), max_length=64, blank=False)
    display_name = models.CharField(_("display name"), max_length=64)
    mailing_list = models.EmailField(_("mailing list"), blank=True,
        help_text=_("The mailing list review requests and discussions "
                    "are sent to."))
    users = models.ManyToManyField(User, blank=True,
                                   related_name="review_groups",
                                   verbose_name=_("users"))
    local_site = models.ForeignKey(LocalSite, blank=True, null=True)

    incoming_request_count = CounterField(
        _('incoming review request count'),
        initializer=lambda g: ReviewRequest.objects.to_group(
            g, local_site=g.local_site).count())

    invite_only = models.BooleanField(_('invite only'), default=False)
    visible = models.BooleanField(default=True)

    objects = ReviewGroupManager()

    def is_accessible_by(self, user):
        "Returns true if the user can access this group."""
        if self.local_site and not self.local_site.is_accessible_by(user):
            return False

        return (not self.invite_only or
                user.is_superuser or
                (user.is_authenticated() and
                 self.users.filter(pk=user.pk).count() > 0))

    def is_mutable_by(self, user):
        """
        Returns whether or not the user can modify or delete the group.

        The group is mutable by the user if they are  an administrator with
        proper permissions, or the group is part of a LocalSite and the user is
        in the admin list.
        """
        return (user.has_perm('reviews.change_group') or
                (self.local_site and self.local_site.is_mutable_by(user)))

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        if self.local_site:
            local_site_name = self.local_site.name
        else:
            local_site_name = None

        return local_site_reverse('group', local_site_name=local_site_name,
                                  kwargs={'name': self.name})

    class Meta:
        unique_together = (('name', 'local_site'),)
        verbose_name = _("review group")
        ordering = ['name']


class DefaultReviewer(models.Model):
    """
    A default reviewer entry automatically adds default reviewers to a
    review request when the diff modifies a file matching the ``file_regex``
    pattern specified.

    This is useful when different groups own different parts of a codebase.
    Adding DefaultReviewer entries ensures that the right people will always
    see the review request and discussions.

    A ``file_regex`` of ``".*"`` will add the specified reviewers by
    default for every review request.

    Note that this is keyed off the same LocalSite as its "repository" member.
    """
    name = models.CharField(_("name"), max_length=64)
    file_regex = models.CharField(_("file regex"), max_length=256,
        help_text=_("File paths are matched against this regular expression "
                    "to determine if these reviewers should be added."))
    repository = models.ManyToManyField(Repository, blank=True)
    groups = models.ManyToManyField(Group, verbose_name=_("default groups"),
                                    blank=True)
    people = models.ManyToManyField(User, verbose_name=_("default people"),
                                    related_name="default_review_paths",
                                    blank=True)
    local_site = models.ForeignKey(LocalSite, blank=True, null=True,
                                   related_name='default_reviewers')

    objects = DefaultReviewerManager()

    def __unicode__(self):
        return self.name


class Screenshot(models.Model):
    """
    A screenshot associated with a review request.

    Like diffs, a screenshot can have comments associated with it.
    These comments are of type :model:`reviews.ScreenshotComment`.
    """
    caption = models.CharField(_("caption"), max_length=256, blank=True)
    draft_caption = models.CharField(_("draft caption"),
                                     max_length=256, blank=True)
    image = models.ImageField(_("image"),
                              upload_to=os.path.join('uploaded', 'images',
                                                     '%Y', '%m', '%d'))

    def get_thumbnail_url(self):
        """
        Returns the URL for the thumbnail, creating it if necessary.
        """
        return thumbnail(self.image)

    def thumb(self):
        """
        Creates a thumbnail of this screenshot and returns the HTML
        output embedding the thumbnail.
        """
        url = self.get_thumbnail_url()
        return mark_safe('<img src="%s" alt="%s" />' % (url, self.caption))
    thumb.allow_tags = True

    def __unicode__(self):
        return u"%s (%s)" % (self.caption, self.image)

    def get_review_request(self):
        try:
            return self.review_request.all()[0]
        except IndexError:
            try:
                return self.inactive_review_request.all()[0]
            except IndexError:
                # Maybe it's on a draft.
                try:
                    draft = self.drafts.get()
                except ReviewRequestDraft.DoesNotExist:
                    draft = self.inactive_drafts.get()

                return draft.review_request

    def get_absolute_url(self):
        review_request = self.get_review_request()

        if review_request.local_site:
            local_site_name = review_request.local_site.name
        else:
            local_site_name = None

        return local_site_reverse(
            'screenshot',
            local_site_name=local_site_name,
            kwargs={
                'review_request_id': review_request.display_id,
                'screenshot_id': self.pk,
            })

    def save(self, **kwargs):
        super(Screenshot, self).save()

        try:
            draft = self.drafts.get()
            draft.timestamp = datetime.now()
            draft.save()
        except ReviewRequestDraft.DoesNotExist:
            pass


class ReviewRequest(models.Model):
    """
    A review request.

    This is one of the primary models in Review Board. Most everything
    is associated with a review request.

    The ReviewRequest model contains detailed information on a review
    request. Some fields are user-modifiable, while some are used for
    internal state.
    """
    PENDING_REVIEW = "P"
    SUBMITTED      = "S"
    DISCARDED      = "D"

    STATUSES = (
        (PENDING_REVIEW, _('Pending Review')),
        (SUBMITTED,      _('Submitted')),
        (DISCARDED,      _('Discarded')),
    )

templates/reviews/comment_issue.html
<div class="issue-state">
  <span class="issue-message"></span>
  <input type="button" value="Fixed" class="issue-button resolve" style="display:none;"/>
  <input type="button" value="Drop" class="issue-button drop" style="display:none;"/>
  <input type="button" value="Re-open" class="issue-button reopen" style="display:none;"/>
</div>
<script language="javascript">
  $(document).ready(function() {
    $("#comment-{{comment.id}}-issue")
        .commentIssue({{review.id}}, {{comment.id}}, "{{comment_type}}", "{{issue_status}}",
                      {{interactive}});
  });
</script>

templates/reviews/comments_dlg.html
{% load i18n %}
<div id="comment-detail" style="display:none;position:absolute;">
 <div id="review_comments">
  <h1 class="title">{% trans "Other reviews" %}</h1>
  <ul id="review_comment_list"></ul>
 </div>
 <form id="draft-form" method="post">
  <h1 class="title">{% trans "Your comment" %}</h1>
  <input type="hidden" name="action" id="comment_action" value="" />
{% if not request.user.is_authenticated %}
{%  url login as login_url %}
  <p>
   {% blocktrans %}You must <a href="{{login_url}}">log in</a> to post
   a comment.{% endblocktrans %}
  </p>
{% endif %}
  <textarea id="comment_text" name="text" rows="6" cols="30"></textarea>
  <div id="comment-issue-options">
   <input type="checkbox" name="comment_issue" id="comment_issue" checked="checked" />
   <label for="comment_issue">{% trans "Open an <u>i</u>ssue" %}</label>
  </div>
  <div class="status"></div>
  <div class="buttons">
   <input type="button" id="comment_save" value="{% trans "Save" %}" />
   <input type="button" id="comment_cancel" value="{% trans "Cancel" %}" />
   <input type="button" id="comment_delete" value="{% trans "Delete" %}" />
  </div>
 </form>
</div>

templates/reviews/dashboard_entry.html
    <tr onclick="javascript:window.location=&quot;{% url dashboard %}?view={{view}}{% if group_name %}&amp;group={{group_name}}{% endif %}&quot;; return false;"{% if selected %} class="selected"{% endif %}>
     <td class="summary {{level}}"><a href="{% url dashboard %}?view={{view}}{% if group_name %}&amp;group={{group_name}}{% endif %}">{% if starred %}<img src="{{MEDIA_URL}}rb/images/star_on.png?{{MEDIA_SERIAL}}" width="16" height="15" alt="" />{% endif %} {{text}}</a></td>
     <td>{% if show_count %}{{count}}{% endif %}</td>
    </tr>

templates/reviews/diff_comment_fragment.html
{% load djblets_utils %}
{% load reviewtags %}
{% load difftags %}
<table class="sidebyside{% ifequal comment.filediff.source_revision PRE_CREATION %} newfile{% endifequal %}">
 <colgroup>
  <col class="line" />
  <col class="left" />
  <col class="line" />
  <col class="right" />
 </colgroup>
 <thead>
  <tr>
   <th colspan="4" class="filename">
    <a href="{{comment.get_absolute_url}}">{{comment.filediff.dest_file}}</a>
    <span class="diffrevision">
{% if comment.interfilediff %}
     (Diff revisions {{comment.filediff.diffset.revision}} - {{comment.interfilediff.diffset.revision}})
{% else %}
     (Diff revision {{comment.filediff.diffset.revision}})
{% endif %}
    </span>
   </th>
  </tr>
 </thead>
{% if chunks.0.meta.headers %}
 <tbody class="diff-header">
  <tr>
{%  ifequal chunks.0.meta.headers.0 chunks.0.meta.headers.1 %}
   <td colspan="4"><pre>{{chunks.0.meta.headers.0}}</pre></td>
{%  else %}
   <td colspan="2"><pre>{{chunks.0.meta.headers.0}}</pre></td>
   <td colspan="2"><pre>{{chunks.0.meta.headers.1}}</pre></td>
{%  endifequal %}
  </tr>
 </tbody>
{% endif %}
{% for chunk in chunks %}
 <tbody class="{{chunk.change}}">
{#  <tr><td colspan="4">{{chunk.meta}}</td></tr> #}
{% for line in chunk.lines %}
  <tr{% ifnotequal chunk.change "equal" %}{% attr "class" %}{% if forloop.first %}first{% endif %} {% if forloop.last %}last{% endif %}{% endattr %}{% endifnotequal %}>
    <th>{{line.1}}</td>
    <td><pre>{{line.2|highlightregion:line.3|showextrawhitespace}}</pre></td>
    <th>{{line.4}}</td>
    <td><pre>{{line.5|highlightregion:line.6|showextrawhitespace}}</pre></td>
  </tr>
{% endfor %}
 </tbody>
{% endfor %}{# chunks #}
</table>

templates/reviews/new_post_review_request.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}
{% block title %}{% trans "New Post-commit Review Request" %}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}rb/css/diffviewer.css?{{MEDIA_SERIAL}}" />
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}rb/css/reviews.css?{{MEDIA_SERIAL}}" />
{% endblock %}

{% block scripts-post %}
<script type="text/javascript">
    var visible = {{fields|safe}};

    function updateFormDisplay() {
        var selection = $("#id_repository").get(0);
        var selectedID = selection.options[selection.selectedIndex].value;

        $("tr[class^=row_]").hide();
        $(visible[selectedID]).each(function() {
            $("tr.row_" + this).show();
        });
    }
    
	function checkbox_clicked(box) { 
		if (box && box.currentTarget && [].indexOf) {
			var rev = box.currentTarget.value, 
				checked = box.currentTarget.checked,
				elrevision = $('#id_revisions'),
				revisions = elrevision.val().split(' '),
				idx;
			//checkbox is unchecked: remove all occurences of rev from list of revisions
			while (!checked && (idx = revisions.indexOf(rev)) != -1) {
				revisions = revisions.slice(0, idx).concat(revisions.slice(idx+1));
			}
			//checkbox is checked: add occurence if not already present
			if (checked && revisions.indexOf(rev) == -1) {
				revisions.push(rev);
			}
			elrevision.val(revisions.join(' ').trim());
		}
	};

	function get_revisions_changed_cb() {
		var last_revisions = {};
		function s2o(s) {
			var i, 
				a = s.split(' '), 
				n = a.length, 
				ret = {};
			for(i = 0; i < n; ++i) {
				ret[a[i]] = true;
			}
			return ret;
		}
		return function() {
			var item,
				new_revisions = s2o($('#id_revisions').val());
			for(item in new_revisions) {
				if (!(item in last_revisions)) {
					//new item -> check
					$('#id_revisions_choice_'+item).attr('checked', true);
				}
			}
			for(item in last_revisions) {
				if (!(item in new_revisions)) {
					//removed item -> uncheck
					$('#id_revisions_choice_'+item).attr('checked', false);
				}
			}
			last_revisions = new_revisions;
		};
	};

    $(document).ready(function() {
        $("#id_repository")
            .change(updateFormDisplay)
            .triggerHandler("change");
        //check checkboxes that were selected on previous page
        var i, 
        	revs = $('#id_revisions').val().split(' ');
        for(i = 0; i < revs.length; ++i) { 
          $('#id_revisions_choice_'+revs[i]).attr('checked', true);
        } 
        $('#id_revisions').bind('keyup', get_revisions_changed_cb());
        //when clicking a checkbox, add revision number to #id_revisions
        $('.revisions_choice_list :input[type="checkbox"]')
            .bind('click', checkbox_clicked);
    });
    
</script>
{% endblock %}

{% block content %}


<form method="post" enctype="multipart/form-data">
{% box "new-post-commit-review-request" %}
 <h1 class="title"> <input type="submit" id="create_button" value="{% trans "Create" %}" /> {% trans "New Post-commit Review Request" %} </h1>
 <div class="main">
  <table>

   <tr class="row_revisions_choice">
    <td colspan="3" class="revisions_choice_list">
      {{form.revisions_choice.errors}}
    </td>
   </tr>

   <tr>
    <td><label for="id_repository">{% trans "Repository" %}:</label></td>
	<td>{{form.repository}}</td>
	<td>{{form.repository.errors}}</td>
   </tr>
   <tr class="row_no_repository_explanation">
    <td></td>
    <td class="help" colspan="2">
     {% blocktrans %}
     You won't be able to add any diffs to this review request. The review
     request will only be usable for reviewing screenshots and other graphic
     files.
     {% endblocktrans %}
    </td>
   </tr>
   
   <tr class="row_scm_user">
    <td><label for="id_scm_user">{{form.scm_user.label}}:</label></td>
    <td>{{form.scm_user}}</td>
    <td>{{form.scm_user.errors}}</td>
   </tr>   
   <tr class="row_scm_user">
    <td></td>
    <td class="help" colspan="2">{{form.scm_user.help_text}}</td>
   </tr>

   <tr class="row_revisions">
    <td><label for="id_revisions">{{form.revisions.label}}:</label></td>
    <td>{{form.revisions}}</td>
    <td>{{form.revisions.errors}}</td>
   </tr>   
   <tr class="row_revisions">
    <td></td>
    <td class="help" colspan="2">{{form.revisions.help_text}}</td>
   </tr>

   <tr class="row_revisions_choice" border="1">
    <td border="1"><label for="id_revisions">{{form.revisions_choice.label}}:</label></td>
    <td border="1"><input class="revisions_choice_button" type="submit" name="load_revisions_button" value="{{form.load_revisions_button}}"/> </td> 
    <td border="1"><input class="revisions_choice_button" type="submit" name="ignore_revisions_button" value="{{form.ignore_revisions_button}}"/>
		   <input class="revisions_choice_button" type="submit" name="showall_revisions_button" value="{{form.showall_revisions_button}}"/>
    </td>
   </tr>
   <tr>
    <td/> 
    <td class="help" colspan="2">{{form.revisions_choice_help}}</td>
   </tr>
   <tr class="row_revisions_choice">
    <td class="revisions_choice_list"></td>
    <td class="revisions_choice_list" valign="baseline" colspan="2">
      {{form.revisions_choice}}
    </td>
   </tr>
  </table>
 </div>
{% endbox %}
</form>

{% endblock %}

templates/reviews/new_review_request.html
{% extends "base.html" %}
{% load djblets_deco %}
{% load i18n %}
{% block title %}{% trans "New Review Request" %}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}rb/css/diffviewer.css?{{MEDIA_SERIAL}}" />
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}rb/css/reviews.css?{{MEDIA_SERIAL}}" />
{% endblock %}

{% block scripts-post %}
<script type="text/javascript">
    var visible = {{fields|safe}};

    function updateFormDisplay() {
        var selection = $("#id_repository").get(0);
        var selectedID = selection.options[selection.selectedIndex].value;

        $("tr[class^=row_]").hide();
        $(visible[selectedID]).each(function() {
            $("tr.row_" + this).show();
        });
    }

    $(document).ready(function() {
        $("#id_repository")
            .change(updateFormDisplay)
            .triggerHandler("change");
    });
</script>
{% endblock %}

{% block content %}
{% box "tip" %}
<h1>{% trans "Tip: Use post-review" %}</h1>
<p>
{% blocktrans %}
 You can simplify creating and updating review requests by using
 <a href="http://www.reviewboard.org/docs/manual/dev/users/tools/post-review/">post-review</a>.
{% endblocktrans %}
</p>
<p>
{% blocktrans %}
 post-review is a command line tool that will help create compatible diffs,
 create new review requests, and update them, effortlessly. It is compatible
 with Windows, Linux, MacOS X, and other unix-like operating systems.
{% endblocktrans %}
</p>
{% endbox %}

<form method="post" action="." enctype="multipart/form-data">
{% box "new-review-request" %}
 <h1 class="title">{% trans "New Review Request" %}</h1>
 <div class="main">
  <table>
   <tr>
    <td><label for="id_repository">{% trans "Repository" %}:</label></td>
	<td>{{form.repository}}</td>
	<td>{{form.repository.errors}}</td>
   </tr>
   <tr class="row_no_repository_explanation">
    <td></td>
    <td class="help" colspan="2">
     {% blocktrans %}
     You won't be able to add any diffs to this review request. The review
     request will only be usable for reviewing screenshots and other graphic
     files.
     {% endblocktrans %}
    </td>
   </tr>
   <tr class="row_changenum">
    <td><label for="id_changenum">{{form.changenum.label}}:</label></td>
    <td>{{form.changenum}}</td>
    <td>{{form.changenum.errors}}</td>
   </tr>
   <tr class="row_basedir">
    <td><label for="id_basedir">{{form.basedir.label}}:</label></td>
    <td>{{form.basedir}}</td>
    <td>{{form.basedir.errors}}</td>
   </tr>
   <tr class="row_basedir">
    <td></td>
    <td class="help" colspan="2">{{form.basedir.help_text}}</td>
   </tr>
   <tr class="row_diff_path">
    <td><label for="id_diff_path">{{form.diff_path.label}}:</label></td>
    <td>{{form.diff_path}}</td>
    <td>{{form.diff_path.errors}}</td>
   </tr>
   <tr class="row_diff_path">
    <td></td>
    <td class="help" colspan="2">{{form.diff_path.help_text}}</td>
   </tr>
   <tr class="row_parent_diff_path">
    <td><label for="id_parent_diff_path">{{form.parent_diff_path.label}}:</label></td>
    <td>{{form.parent_diff_path}}</td>
    <td>{{form.parent_diff_path.errors}}</td>
   </tr>
   <tr class="row_parent_diff_path">
    <td></td>
    <td class="help" colspan="2">{{form.parent_diff_path.help_text}}</td>
   </tr>
  </table>
 </div>
{% endbox %}
 <div class="prefsbuttons">
  <input type="submit" value="{% trans "Create Review Request" %}" />
 </div>
</form>

{% endblock %}